database:
  host: "demo-postgres.cr602kscub2u.us-east-1.rds.amazonaws.com"
  port: 5432
  name: "postgres"
  user: "postgres"
  password: "Laraybella05"

openai:
  key: "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"
